Repository nijesmik/algo-study-season-3, pull requests merged in 2024-08, with the labels that each got.

#29 [week08] nijesmik
  nijesmik/week08/110_옮기기.js
  nijesmik/week08/무지의_먹방_라이브.js
  nijesmik/week08/주차_요금_계산.js
  nijesmik/week08/최댓값과_최솟값.js
Labels: all solved, correction completed

#32 [week09] damdam6
  damdam6/week09/3xn타일링.java
  damdam6/week09/JadenCase 문자열 만들기.js
  damdam6/week09/N개의 최소공배수.js
  damdam6/week09/카펫.js
  damdam6/week09/트리 순회.java
  damdam6/week09/표 편집.js
  damdam6/week09/프렌즈4블록.js
Labels: all solved

#34 [week10] damdam6
  damdam6/week10/구명보트.js
  damdam6/week10/점프와 순간이동.js
  damdam6/week10/호텔 방 배정.java
Labels: partially solved

#35 [week10] Damongsanga
  Damongsanga/week10/길_찾기_게임.java
  Damongsanga/week10/단어변환.java
  Damongsanga/week10/블록게임.java
  Damongsanga/week10/호텔_방_배정.java
Labels: all solved

#36 [week10] nijesmik
  nijesmik/week10/게임_맵_최단거리.js
  nijesmik/week10/단어_변환.js
  nijesmik/week10/방문_길이.js
  nijesmik/week10/호텔_방_배정.js
  nijesmik/week10/호텔_방_배정/Solution.java
Labels: all solved

#37 [week10] Minah7
  Minah7/week07/문자열 압축 해제.java
  Minah7/week07/수학 문제.java
  Minah7/week07/정리 정돈을 좋아하는 k씨.java
  Minah7/week07/트리 위의 게임.java
  Minah7/week08/110 옮기기.java
  Minah7/week08/귤 고르기.java
  Minah7/week08/네트워크.java
  Minah7/week08/무지의 먹방 라이브.java
  Minah7/week10/괄호의_값.java
  Minah7/week10/단어 변환.java
  Minah7/week10/연산자_끼워넣기.java
  Minah7/week10/호텔 방 배정.java
Labels: all solved

#38 [week11] nijesmik
  nijesmik/week11/구명보트.js
  nijesmik/week11/부대복귀.js
  nijesmik/week11/자동완성/solution.js
  nijesmik/week11/자동완성/solution2.js
  nijesmik/week11/파일명_정렬.js
Labels: all solved

#40 [week11] Minah7
  Minah7/week11/가르침.java
  Minah7/week11/부대복귀.java
  Minah7/week11/빗물.java
  Minah7/week11/자동완성.java
Labels: all solved
